spring:
  application:
    name: spring-gateway-oauth2-keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: callme-service
          uri: http://127.0.0.1:8040
          predicates:
            - Path=/callme/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-test-scope:
            provider: keycloak
            client-id: user-with-test-scope
            client-secret: b9aaf6f5-6a77-4488-9086-8680d93af1b9
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

          keycloak-without-test-scope:
            provider: keycloak
            client-id: user-without-test-scope
            client-secret: bdecb169-3981-4441-a9a4-d3c7e176d791
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server:
  port : 9020

#Actuator health check    
management:
  endpoints:
    web:
      exposure:
        include: "*"